# Generated by Django 2.0.4 on 2019-08-01 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportVisitHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=250)),
                ('ip', models.CharField(max_length=250)),
                ('request_type', models.CharField(max_length=10)),
                ('location', jsonfield.fields.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='campaigndoners',
            name='city',
            field=models.CharField(default='Hyderabad', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaigndoners',
            name='state',
            field=models.CharField(default='Telangana', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventgroupmembers',
            name='state',
            field=models.CharField(default='Telangana', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportgroupmembers',
            name='state',
            field=models.CharField(default='Telangana', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaigndoners',
            name='payment_status',
            field=models.CharField(choices=[('created', 'Created'), ('captured', 'Captured'), ('failed', 'Failed'), ('refund', 'Refund')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaignfundraiser',
            name='sensitivity',
            field=models.CharField(choices=[('high sensitive', 'High'), ('moderate', 'Moderate'), ('charity', 'Charity')], max_length=40),
        ),
        migrations.AlterField(
            model_name='event',
            name='sensitivity',
            field=models.CharField(choices=[('high sensitive', 'High'), ('moderate', 'Moderate'), ('charity', 'Charity')], max_length=40),
        ),
        migrations.AlterField(
            model_name='supportgroup',
            name='sensitivity',
            field=models.CharField(choices=[('high sensitive', 'High'), ('moderate', 'Moderate'), ('charity', 'Charity')], max_length=40),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='WithdrawalRequest'),
        ),
        migrations.AddField(
            model_name='supportvisithistory',
            name='support_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fundraiser.SupportGroup'),
        ),
        migrations.AddField(
            model_name='supportvisithistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
