# Generated by Django 2.0.4 on 2019-09-10 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0002_campaignsubcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignsubcategory',
            old_name='category',
            new_name='sub_category',
        ),
    ]
