# Generated by Django 2.0.4 on 2019-09-10 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0003_auto_20190910_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignsubcategory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fundraiser.CampaignCategory'),
            preserve_default=False,
        ),
    ]
