# Generated by Django 2.0.4 on 2019-09-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0004_campaignsubcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignfundraiser',
            name='url_text',
            field=models.CharField(default='test', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='url_text',
            field=models.CharField(default='test', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportgroup',
            name='url_text',
            field=models.CharField(default='test', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
