# Generated by Django 2.0.4 on 2019-08-27 08:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0004_bannerimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashfreePaymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=250, null=True)),
                ('secrate_key', models.CharField(max_length=250, null=True)),
                ('payment_mode', models.CharField(choices=[('TEST', 'TEST'), ('PROD', 'PROD')], max_length=250, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='campaigndoners',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100)]),
        ),
    ]
