# Generated by Django 2.0.4 on 2019-09-11 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0005_auto_20190911_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignfundraiser',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fundraiser.CampaignSubCategory'),
        ),
    ]
