# Generated by Django 2.0.4 on 2019-08-27 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0006_abcd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='abcd',
        ),
    ]
