# Generated by Django 2.0.4 on 2019-08-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0007_delete_abcd'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigndoners',
            name='order_id',
            field=models.CharField(editable=False, max_length=20, null=True),
        ),
    ]
