# Generated by Django 2.0.4 on 2019-09-19 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0007_auto_20190911_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignFundRaiserVisitHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=250)),
                ('ip', models.CharField(max_length=250)),
                ('request_type', models.CharField(max_length=10)),
                ('location', jsonfield.fields.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign_fundraiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fundraiser.CampaignFundRaiser')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventVisitHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=250)),
                ('ip', models.CharField(max_length=250)),
                ('request_type', models.CharField(max_length=10)),
                ('location', jsonfield.fields.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fundraiser.Event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
