# Generated by Django 2.0.4 on 2019-08-27 11:03

from django.db import migrations, models
import fundraiser.models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0008_campaigndoners_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigndoners',
            name='order_id',
            field=models.CharField(default=fundraiser.models.increment_booking_number, editable=False, max_length=20, null=True),
        ),
    ]
