# Generated by Django 2.0.4 on 2019-10-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0008_campaignfundraiservisithistory_eventvisithistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignfundraiser',
            name='address_proof_image',
            field=models.ImageField(null=True, upload_to='campaign_fund_raiser_document'),
        ),
        migrations.AddField(
            model_name='campaignfundraiser',
            name='cancelled_cheque_image',
            field=models.ImageField(null=True, upload_to='campaign_fund_raiser_document'),
        ),
    ]
