# Generated by Django 2.0.4 on 2019-09-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0009_auto_20190827_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigndoners',
            name='country',
            field=models.CharField(default='India', max_length=50),
        ),
    ]
