# Generated by Django 2.0.4 on 2019-10-04 11:07

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0009_auto_20191004_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignfundraiservisithistory',
            name='ip',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='campaignfundraiservisithistory',
            name='location',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaignfundraiservisithistory',
            name='path',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='campaignfundraiservisithistory',
            name='request_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='eventvisithistory',
            name='ip',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='eventvisithistory',
            name='location',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventvisithistory',
            name='path',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='eventvisithistory',
            name='request_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='supportvisithistory',
            name='ip',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='supportvisithistory',
            name='location',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supportvisithistory',
            name='path',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='supportvisithistory',
            name='request_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
