# Generated by Django 2.0.4 on 2019-09-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0010_campaigndoners_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigndoners',
            name='facbook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='campaigndoners',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
