# Generated by Django 2.0.4 on 2019-10-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0010_auto_20191004_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigndoners',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='campaignfundraiservisithistory',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eventgroupmembers',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eventvisithistory',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supportgroupmembers',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supportvisithistory',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
