# Generated by Django 2.0.4 on 2019-10-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0011_auto_20191004_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignfundraiser',
            name='custome_note',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='custome_note',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='supportgroup',
            name='custome_note',
            field=models.TextField(null=True),
        ),
    ]
