# Generated by Django 2.0.4 on 2019-10-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0011_auto_20190908_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgroupmembers',
            name='country',
            field=models.CharField(default='India', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventgroupmembers',
            name='facbook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventgroupmembers',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
