# Generated by Django 2.0.4 on 2019-10-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0012_auto_20191004_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignfundraiser',
            name='enable_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='enable_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supportgroup',
            name='enable_comment',
            field=models.BooleanField(default=True),
        ),
    ]
