# Generated by Django 2.0.4 on 2019-10-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0013_auto_20191011_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignfundraiser',
            name='is_end_goal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_end_goal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportgroup',
            name='is_end_goal',
            field=models.BooleanField(default=False),
        ),
    ]
