# Generated by Django 2.0.4 on 2019-10-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0014_auto_20191012_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_democracy_commission', models.FloatField()),
                ('our_democracy_gst', models.FloatField()),
                ('payment_gateway_charges', models.FloatField()),
                ('payment_gateway_gst', models.FloatField()),
            ],
        ),
    ]
