# Generated by Django 2.0.4 on 2019-10-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0015_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigndoners',
            name='our_democracy_commission',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='campaigndoners',
            name='our_democracy_commission_in_rs',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='campaigndoners',
            name='our_democracy_gst',
            field=models.FloatField(default=18),
        ),
        migrations.AddField(
            model_name='campaigndoners',
            name='our_democracy_gst_in_rs',
            field=models.FloatField(default=18),
        ),
        migrations.AddField(
            model_name='campaigndoners',
            name='payment_gateway_charges',
            field=models.FloatField(default=3),
        ),
        migrations.AddField(
            model_name='campaigndoners',
            name='payment_gateway_charges_in_rs',
            field=models.FloatField(default=3),
        ),
        migrations.AddField(
            model_name='campaigndoners',
            name='payment_gateway_gst',
            field=models.FloatField(default=18),
        ),
        migrations.AddField(
            model_name='campaigndoners',
            name='payment_gateway_gst_in_rs',
            field=models.FloatField(default=18),
        ),
        migrations.AlterField(
            model_name='commission',
            name='our_democracy_commission',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='commission',
            name='our_democracy_gst',
            field=models.FloatField(default=18),
        ),
        migrations.AlterField(
            model_name='commission',
            name='payment_gateway_charges',
            field=models.FloatField(default=3),
        ),
        migrations.AlterField(
            model_name='commission',
            name='payment_gateway_gst',
            field=models.FloatField(default=18),
        ),
    ]
