# Generated by Django 2.0.4 on 2019-10-14 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0016_auto_20191014_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigndoners',
            name='our_democracy_commission',
        ),
        migrations.RemoveField(
            model_name='campaigndoners',
            name='our_democracy_commission_in_rs',
        ),
        migrations.RemoveField(
            model_name='campaigndoners',
            name='our_democracy_gst',
        ),
        migrations.RemoveField(
            model_name='campaigndoners',
            name='our_democracy_gst_in_rs',
        ),
        migrations.RemoveField(
            model_name='campaigndoners',
            name='payment_gateway_charges',
        ),
        migrations.RemoveField(
            model_name='campaigndoners',
            name='payment_gateway_charges_in_rs',
        ),
        migrations.RemoveField(
            model_name='campaigndoners',
            name='payment_gateway_gst',
        ),
        migrations.RemoveField(
            model_name='campaigndoners',
            name='payment_gateway_gst_in_rs',
        ),
    ]
