# Generated by Django 2.0.4 on 2019-10-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0017_auto_20191014_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigndoners',
            name='our_democracy_commission',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaigndoners',
            name='our_democracy_commission_in_rs',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaigndoners',
            name='our_democracy_gst',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaigndoners',
            name='our_democracy_gst_in_rs',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaigndoners',
            name='payment_gateway_charges',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaigndoners',
            name='payment_gateway_charges_in_rs',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaigndoners',
            name='payment_gateway_gst',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaigndoners',
            name='payment_gateway_gst_in_rs',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
