# Generated by Django 2.0.4 on 2019-10-16 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fundraiser.models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0018_auto_20191014_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialCampaignDoners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=20)),
                ('facbook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('indian_citizen', models.BooleanField(default=True)),
                ('is_hide_me', models.BooleanField(default=False)),
                ('order_id', models.CharField(default=fundraiser.models.increment_booking_number, editable=False, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign_fund_raiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fundraiser.CampaignFundRaiser')),
                ('doner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
