# Generated by Django 2.0.4 on 2019-10-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0019_potentialcampaigndoners'),
    ]

    operations = [
        migrations.AddField(
            model_name='potentialcampaigndoners',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
