# Generated by Django 2.0.4 on 2019-10-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0020_potentialcampaigndoners_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigndoners',
            name='pan_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
