# Generated by Django 2.0.4 on 2019-10-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0021_campaigndoners_pan_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='potentialcampaigndoners',
            name='sent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
