# Generated by Django 2.0.4 on 2019-10-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0022_potentialcampaigndoners_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigndoners',
            name='payment_mode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
