# Generated by Django 2.0.4 on 2019-10-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0023_campaigndoners_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignfundraiser',
            name='address_proof_type',
            field=models.CharField(choices=[('Adhaar Card', 'Adhaar Card'), ('Passport', 'Passport'), ('Electricity Bill', 'Electricity Bill'), ('Driving License', 'Driving License')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='campaignfundraiser',
            name='pancard_image',
            field=models.ImageField(null=True, upload_to='campaign_fund_raiser_document'),
        ),
        migrations.AddField(
            model_name='campaignfundraiser',
            name='pancard_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
