# Generated by Django 2.0.4 on 2019-10-18 10:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0024_auto_20191018_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignbuzz',
            name='buzz',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='campaignupdates',
            name='about',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='eventbuzz',
            name='buzz',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='eventupdates',
            name='about',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='supportbuzz',
            name='buzz',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='supportupdates',
            name='about',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
