# Generated by Django 2.0.4 on 2019-10-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0025_auto_20191018_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignfundraiser',
            name='address_proof_image',
            field=models.FileField(null=True, upload_to='campaign_fund_raiser_document'),
        ),
        migrations.AlterField(
            model_name='campaignfundraiser',
            name='cancelled_cheque_image',
            field=models.FileField(null=True, upload_to='campaign_fund_raiser_document'),
        ),
        migrations.AlterField(
            model_name='campaignfundraiser',
            name='pancard_image',
            field=models.FileField(null=True, upload_to='campaign_fund_raiser_document'),
        ),
    ]
