# Generated by Django 2.0.4 on 2019-10-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0026_auto_20191018_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignbuzz',
            name='buzz',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaignupdates',
            name='about',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='eventbuzz',
            name='buzz',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='eventupdates',
            name='about',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='supportbuzz',
            name='buzz',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='supportupdates',
            name='about',
            field=models.TextField(),
        ),
    ]
